import pandas as pd
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
print("Loaded!")
print("Ratings shape:", ratings.shape)
print("Movies shape:", movies.shape)
df = pd.merge(ratings, movies, on='movieId')
print("Merged!")
df = df.dropna()
df = df.drop_duplicates()
df = df.drop(columns=['timestamp'])
print("Cleaned!")
user_movie_matrix = df.pivot_table(index='userId',columns='title',values='rating').fillna(0)
print("Matrix built!")
print("Matrix shape:", user_movie_matrix.shape)
df.to_csv('cleaned_data.csv', index=False)
user_movie_matrix.to_pickle('user_movie_matrix.pkl')
print("Saved! All done.")