import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

bollywood_data = [
    {"movie_name":"3 Idiots","genre":"Comedy Drama","lead_actor":"Aamir Khan","director":"Rajkumar Hirani","imdb_rating":8.4,"verdict":"Blockbuster","release_year":2009},
    {"movie_name":"Dangal","genre":"Drama Sports","lead_actor":"Aamir Khan","director":"Nitesh Tiwari","imdb_rating":8.3,"verdict":"Blockbuster","release_year":2016},
    {"movie_name":"PK","genre":"Comedy Drama","lead_actor":"Aamir Khan","director":"Rajkumar Hirani","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2014},
    {"movie_name":"Taare Zameen Par","genre":"Drama","lead_actor":"Aamir Khan","director":"Aamir Khan","imdb_rating":8.4,"verdict":"Blockbuster","release_year":2007},
    {"movie_name":"Lagaan","genre":"Drama Sports","lead_actor":"Aamir Khan","director":"Ashutosh Gowariker","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2001},
    {"movie_name":"Dhoom 3","genre":"Action Thriller","lead_actor":"Aamir Khan","director":"Vijay Krishna Acharya","imdb_rating":5.9,"verdict":"Blockbuster","release_year":2013},
    {"movie_name":"Pathaan","genre":"Action Thriller","lead_actor":"Shah Rukh Khan","director":"Siddharth Anand","imdb_rating":7.0,"verdict":"Blockbuster","release_year":2023},
    {"movie_name":"Jawan","genre":"Action Drama","lead_actor":"Shah Rukh Khan","director":"Atlee","imdb_rating":7.1,"verdict":"Blockbuster","release_year":2023},
    {"movie_name":"Dunki","genre":"Drama Comedy","lead_actor":"Shah Rukh Khan","director":"Rajkumar Hirani","imdb_rating":6.5,"verdict":"Hit","release_year":2023},
    {"movie_name":"Dilwale Dulhania Le Jayenge","genre":"Romance Drama","lead_actor":"Shah Rukh Khan","director":"Aditya Chopra","imdb_rating":8.1,"verdict":"Blockbuster","release_year":1995},
    {"movie_name":"Kabhi Khushi Kabhie Gham","genre":"Romance Drama","lead_actor":"Shah Rukh Khan","director":"Karan Johar","imdb_rating":7.4,"verdict":"Blockbuster","release_year":2001},
    {"movie_name":"My Name Is Khan","genre":"Drama","lead_actor":"Shah Rukh Khan","director":"Karan Johar","imdb_rating":7.9,"verdict":"Blockbuster","release_year":2010},
    {"movie_name":"Chennai Express","genre":"Action Comedy","lead_actor":"Shah Rukh Khan","director":"Rohit Shetty","imdb_rating":5.9,"verdict":"Blockbuster","release_year":2013},
    {"movie_name":"KGF Chapter 1","genre":"Action Drama","lead_actor":"Yash","director":"Prashanth Neel","imdb_rating":8.2,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"KGF Chapter 2","genre":"Action Drama","lead_actor":"Yash","director":"Prashanth Neel","imdb_rating":8.4,"verdict":"Blockbuster","release_year":2022},
    {"movie_name":"RRR","genre":"Action Drama","lead_actor":"Ram Charan","director":"SS Rajamouli","imdb_rating":7.9,"verdict":"Blockbuster","release_year":2022},
    {"movie_name":"Baahubali The Beginning","genre":"Action Drama","lead_actor":"Prabhas","director":"SS Rajamouli","imdb_rating":8.0,"verdict":"Blockbuster","release_year":2015},
    {"movie_name":"Baahubali The Conclusion","genre":"Action Drama","lead_actor":"Prabhas","director":"SS Rajamouli","imdb_rating":8.2,"verdict":"Blockbuster","release_year":2017},
    {"movie_name":"Pushpa The Rise","genre":"Action Drama","lead_actor":"Allu Arjun","director":"Sukumar","imdb_rating":7.6,"verdict":"Blockbuster","release_year":2021},
    {"movie_name":"Pushpa The Rule","genre":"Action Drama","lead_actor":"Allu Arjun","director":"Sukumar","imdb_rating":7.8,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Animal","genre":"Action Drama","lead_actor":"Ranbir Kapoor","director":"Sandeep Reddy Vanga","imdb_rating":6.9,"verdict":"Blockbuster","release_year":2023},
    {"movie_name":"Brahmastra","genre":"Action Fantasy","lead_actor":"Ranbir Kapoor","director":"Ayan Mukerji","imdb_rating":5.6,"verdict":"Hit","release_year":2022},
    {"movie_name":"Sanju","genre":"Biography Drama","lead_actor":"Ranbir Kapoor","director":"Rajkumar Hirani","imdb_rating":7.7,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Yeh Jawaani Hai Deewani","genre":"Romance Drama","lead_actor":"Ranbir Kapoor","director":"Ayan Mukerji","imdb_rating":7.4,"verdict":"Blockbuster","release_year":2013},
    {"movie_name":"Stree","genre":"Horror Comedy","lead_actor":"Rajkummar Rao","director":"Amar Kaushik","imdb_rating":7.8,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Stree 2","genre":"Horror Comedy","lead_actor":"Shraddha Kapoor","director":"Amar Kaushik","imdb_rating":8.0,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Bhediya","genre":"Horror Comedy","lead_actor":"Varun Dhawan","director":"Amar Kaushik","imdb_rating":6.8,"verdict":"Hit","release_year":2022},
    {"movie_name":"Munjya","genre":"Horror Comedy","lead_actor":"Sharvari Wagh","director":"Aditya Sarpotdar","imdb_rating":7.2,"verdict":"Hit","release_year":2024},
    {"movie_name":"Sholay","genre":"Action Drama","lead_actor":"Amitabh Bachchan","director":"Ramesh Sippy","imdb_rating":8.2,"verdict":"Blockbuster","release_year":1975},
    {"movie_name":"Deewar","genre":"Action Drama","lead_actor":"Amitabh Bachchan","director":"Yash Chopra","imdb_rating":8.1,"verdict":"Blockbuster","release_year":1975},
    {"movie_name":"Zanjeer","genre":"Action Drama","lead_actor":"Amitabh Bachchan","director":"Prakash Mehra","imdb_rating":7.8,"verdict":"Blockbuster","release_year":1973},
    {"movie_name":"Pink","genre":"Drama Thriller","lead_actor":"Amitabh Bachchan","director":"Aniruddha Roy Chowdhury","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2016},
    {"movie_name":"War","genre":"Action Thriller","lead_actor":"Hrithik Roshan","director":"Siddharth Anand","imdb_rating":6.5,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Krrish","genre":"Action Fantasy","lead_actor":"Hrithik Roshan","director":"Rakesh Roshan","imdb_rating":6.5,"verdict":"Blockbuster","release_year":2006},
    {"movie_name":"Zindagi Na Milegi Dobara","genre":"Drama Comedy","lead_actor":"Hrithik Roshan","director":"Zoya Akhtar","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2011},
    {"movie_name":"Jodhaa Akbar","genre":"Romance Drama","lead_actor":"Hrithik Roshan","director":"Ashutosh Gowariker","imdb_rating":7.5,"verdict":"Blockbuster","release_year":2008},
    {"movie_name":"Gully Boy","genre":"Drama Music","lead_actor":"Ranveer Singh","director":"Zoya Akhtar","imdb_rating":8.0,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Padmaavat","genre":"Drama Romance","lead_actor":"Ranveer Singh","director":"Sanjay Leela Bhansali","imdb_rating":7.0,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Bajirao Mastani","genre":"Romance Drama","lead_actor":"Ranveer Singh","director":"Sanjay Leela Bhansali","imdb_rating":7.2,"verdict":"Blockbuster","release_year":2015},
    {"movie_name":"Band Baaja Baaraat","genre":"Romance Comedy","lead_actor":"Ranveer Singh","director":"Maneesh Sharma","imdb_rating":7.3,"verdict":"Hit","release_year":2010},
    {"movie_name":"Queen","genre":"Drama Comedy","lead_actor":"Kangana Ranaut","director":"Vikas Bahl","imdb_rating":8.2,"verdict":"Blockbuster","release_year":2014},
    {"movie_name":"Tanu Weds Manu","genre":"Romance Comedy","lead_actor":"Kangana Ranaut","director":"Aanand L Rai","imdb_rating":7.4,"verdict":"Hit","release_year":2011},
    {"movie_name":"Dil Dhadakne Do","genre":"Drama Comedy","lead_actor":"Ranveer Singh","director":"Zoya Akhtar","imdb_rating":7.6,"verdict":"Hit","release_year":2015},
    {"movie_name":"Udta Punjab","genre":"Drama Thriller","lead_actor":"Shahid Kapoor","director":"Abhishek Chaubey","imdb_rating":8.0,"verdict":"Hit","release_year":2016},
    {"movie_name":"Kabir Singh","genre":"Romance Drama","lead_actor":"Shahid Kapoor","director":"Sandeep Reddy Vanga","imdb_rating":7.1,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Haider","genre":"Drama Thriller","lead_actor":"Shahid Kapoor","director":"Vishal Bhardwaj","imdb_rating":8.1,"verdict":"Hit","release_year":2014},
    {"movie_name":"Kaminey","genre":"Action Thriller","lead_actor":"Shahid Kapoor","director":"Vishal Bhardwaj","imdb_rating":7.7,"verdict":"Hit","release_year":2009},
    {"movie_name":"Andhadhun","genre":"Thriller Comedy","lead_actor":"Ayushmann Khurrana","director":"Sriram Raghavan","imdb_rating":8.3,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Badhaai Ho","genre":"Comedy Drama","lead_actor":"Ayushmann Khurrana","director":"Amit Sharma","imdb_rating":7.9,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Article 15","genre":"Drama Thriller","lead_actor":"Ayushmann Khurrana","director":"Anubhav Sinha","imdb_rating":8.1,"verdict":"Hit","release_year":2019},
    {"movie_name":"Dream Girl","genre":"Comedy","lead_actor":"Ayushmann Khurrana","director":"Raaj Shaandilyaa","imdb_rating":6.9,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Vicky Donor","genre":"Comedy Drama","lead_actor":"Ayushmann Khurrana","director":"Shoojit Sircar","imdb_rating":7.4,"verdict":"Hit","release_year":2012},
    {"movie_name":"Lunchbox","genre":"Drama Romance","lead_actor":"Irrfan Khan","director":"Ritesh Batra","imdb_rating":7.8,"verdict":"Hit","release_year":2013},
    {"movie_name":"Piku","genre":"Drama Comedy","lead_actor":"Amitabh Bachchan","director":"Shoojit Sircar","imdb_rating":7.9,"verdict":"Blockbuster","release_year":2015},
    {"movie_name":"October","genre":"Drama Romance","lead_actor":"Varun Dhawan","director":"Shoojit Sircar","imdb_rating":7.6,"verdict":"Average","release_year":2018},
    {"movie_name":"Badla","genre":"Thriller Drama","lead_actor":"Amitabh Bachchan","director":"Sujoy Ghosh","imdb_rating":7.9,"verdict":"Hit","release_year":2019},
    {"movie_name":"Kahaani","genre":"Thriller Drama","lead_actor":"Vidya Balan","director":"Sujoy Ghosh","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2012},
    {"movie_name":"Tumhari Sulu","genre":"Drama Comedy","lead_actor":"Vidya Balan","director":"Suresh Triveni","imdb_rating":7.4,"verdict":"Hit","release_year":2017},
    {"movie_name":"Dirty Picture","genre":"Biography Drama","lead_actor":"Vidya Balan","director":"Milan Luthria","imdb_rating":6.8,"verdict":"Blockbuster","release_year":2011},
    {"movie_name":"Drishyam","genre":"Thriller Drama","lead_actor":"Ajay Devgn","director":"Nishikant Kamat","imdb_rating":8.2,"verdict":"Blockbuster","release_year":2015},
    {"movie_name":"Drishyam 2","genre":"Thriller Drama","lead_actor":"Ajay Devgn","director":"Abhishek Pathak","imdb_rating":8.0,"verdict":"Blockbuster","release_year":2022},
    {"movie_name":"Golmaal","genre":"Comedy","lead_actor":"Ajay Devgn","director":"Rohit Shetty","imdb_rating":7.3,"verdict":"Blockbuster","release_year":2006},
    {"movie_name":"Singham","genre":"Action Drama","lead_actor":"Ajay Devgn","director":"Rohit Shetty","imdb_rating":6.8,"verdict":"Blockbuster","release_year":2011},
    {"movie_name":"Tanhaji","genre":"Action Drama","lead_actor":"Ajay Devgn","director":"Om Raut","imdb_rating":7.0,"verdict":"Blockbuster","release_year":2020},
    {"movie_name":"Uri The Surgical Strike","genre":"Action Drama","lead_actor":"Vicky Kaushal","director":"Aditya Dhar","imdb_rating":8.2,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Sam Bahadur","genre":"Biography Drama","lead_actor":"Vicky Kaushal","director":"Meghna Gulzar","imdb_rating":7.8,"verdict":"Hit","release_year":2023},
    {"movie_name":"Raazi","genre":"Thriller Drama","lead_actor":"Alia Bhatt","director":"Meghna Gulzar","imdb_rating":7.9,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Gangubai Kathiawadi","genre":"Biography Drama","lead_actor":"Alia Bhatt","director":"Sanjay Leela Bhansali","imdb_rating":7.4,"verdict":"Blockbuster","release_year":2022},
    {"movie_name":"Highway","genre":"Drama Romance","lead_actor":"Alia Bhatt","director":"Imtiaz Ali","imdb_rating":8.0,"verdict":"Hit","release_year":2014},
    {"movie_name":"Student Of The Year","genre":"Romance Drama","lead_actor":"Alia Bhatt","director":"Karan Johar","imdb_rating":4.7,"verdict":"Average","release_year":2012},
    {"movie_name":"Rocky Aur Rani Ki Prem Kahani","genre":"Romance Drama","lead_actor":"Ranveer Singh","director":"Karan Johar","imdb_rating":6.6,"verdict":"Hit","release_year":2023},
    {"movie_name":"Kalki 2898 AD","genre":"Action SciFi","lead_actor":"Prabhas","director":"Nag Ashwin","imdb_rating":6.9,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Adipurush","genre":"Action Mythology","lead_actor":"Prabhas","director":"Om Raut","imdb_rating":3.5,"verdict":"Flop","release_year":2023},
    {"movie_name":"Salaar","genre":"Action Drama","lead_actor":"Prabhas","director":"Prashanth Neel","imdb_rating":6.4,"verdict":"Hit","release_year":2023},
    {"movie_name":"Tiger Zinda Hai","genre":"Action Thriller","lead_actor":"Salman Khan","director":"Ali Abbas Zafar","imdb_rating":6.0,"verdict":"Blockbuster","release_year":2017},
    {"movie_name":"Bajrangi Bhaijaan","genre":"Drama Comedy","lead_actor":"Salman Khan","director":"Kabir Khan","imdb_rating":8.0,"verdict":"Blockbuster","release_year":2015},
    {"movie_name":"Sultan","genre":"Drama Sports","lead_actor":"Salman Khan","director":"Ali Abbas Zafar","imdb_rating":6.9,"verdict":"Blockbuster","release_year":2016},
    {"movie_name":"Dabangg","genre":"Action Comedy","lead_actor":"Salman Khan","director":"Abhinav Kashyap","imdb_rating":6.8,"verdict":"Blockbuster","release_year":2010},
    {"movie_name":"Wanted","genre":"Action Thriller","lead_actor":"Salman Khan","director":"Prabhu Deva","imdb_rating":6.6,"verdict":"Blockbuster","release_year":2009},
    {"movie_name":"Kisi Ka Bhai Kisi Ki Jaan","genre":"Action Comedy","lead_actor":"Salman Khan","director":"Farhad Samji","imdb_rating":3.8,"verdict":"Flop","release_year":2023},
    {"movie_name":"Tiger 3","genre":"Action Thriller","lead_actor":"Salman Khan","director":"Maneesh Sharma","imdb_rating":5.4,"verdict":"Hit","release_year":2023},
    {"movie_name":"Devara","genre":"Action Drama","lead_actor":"Jr NTR","director":"Koratala Siva","imdb_rating":6.1,"verdict":"Average","release_year":2024},
    {"movie_name":"Leo","genre":"Action Thriller","lead_actor":"Vijay","director":"Lokesh Kanagaraj","imdb_rating":7.2,"verdict":"Blockbuster","release_year":2023},
    {"movie_name":"Jailer","genre":"Action Drama","lead_actor":"Rajinikanth","director":"Nelson Dilipkumar","imdb_rating":7.1,"verdict":"Blockbuster","release_year":2023},
    {"movie_name":"Vikram","genre":"Action Thriller","lead_actor":"Kamal Haasan","director":"Lokesh Kanagaraj","imdb_rating":8.4,"verdict":"Blockbuster","release_year":2022},
    {"movie_name":"Varisu","genre":"Drama Action","lead_actor":"Vijay","director":"Vamshi Paidipally","imdb_rating":6.3,"verdict":"Hit","release_year":2023},
    {"movie_name":"Laal Singh Chaddha","genre":"Drama Comedy","lead_actor":"Aamir Khan","director":"Advait Chandan","imdb_rating":6.2,"verdict":"Flop","release_year":2022},
    {"movie_name":"Thugs Of Hindostan","genre":"Action Adventure","lead_actor":"Aamir Khan","director":"Vijay Krishna Acharya","imdb_rating":3.1,"verdict":"Flop","release_year":2018},
    {"movie_name":"Article 370","genre":"Thriller Drama","lead_actor":"Yami Gautam","director":"Aditya Suhas Jambhale","imdb_rating":8.2,"verdict":"Hit","release_year":2024},
    {"movie_name":"12th Fail","genre":"Drama Biography","lead_actor":"Vikrant Massey","director":"Vidhu Vinod Chopra","imdb_rating":9.0,"verdict":"Blockbuster","release_year":2023},
    {"movie_name":"Fukrey","genre":"Comedy Drama","lead_actor":"Pulkit Samrat","director":"Mrighdeep Singh Lamba","imdb_rating":7.7,"verdict":"Hit","release_year":2013},
    {"movie_name":"Fukrey Returns","genre":"Comedy Drama","lead_actor":"Pulkit Samrat","director":"Mrighdeep Singh Lamba","imdb_rating":6.7,"verdict":"Hit","release_year":2017},
    {"movie_name":"Fukrey 3","genre":"Comedy Drama","lead_actor":"Pulkit Samrat","director":"Mrighdeep Singh Lamba","imdb_rating":6.5,"verdict":"Hit","release_year":2023},
    {"movie_name":"Hera Pheri","genre":"Comedy Drama","lead_actor":"Akshay Kumar","director":"Priyadarshan","imdb_rating":8.2,"verdict":"Blockbuster","release_year":2000},
    {"movie_name":"Phir Hera Pheri","genre":"Comedy Drama","lead_actor":"Akshay Kumar","director":"Neeraj Vora","imdb_rating":7.8,"verdict":"Blockbuster","release_year":2006},
    {"movie_name":"Toilet Ek Prem Katha","genre":"Drama Comedy","lead_actor":"Akshay Kumar","director":"Shree Narayan Singh","imdb_rating":6.1,"verdict":"Hit","release_year":2017},
    {"movie_name":"Kesari","genre":"Action Drama","lead_actor":"Akshay Kumar","director":"Anurag Singh","imdb_rating":7.1,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Mission Mangal","genre":"Drama Biography","lead_actor":"Akshay Kumar","director":"Jagan Shakti","imdb_rating":6.5,"verdict":"Blockbuster","release_year":2019},
    {"movie_name":"Sooryavanshi","genre":"Action Drama","lead_actor":"Akshay Kumar","director":"Rohit Shetty","imdb_rating":5.7,"verdict":"Blockbuster","release_year":2021},
    {"movie_name":"Bade Miyan Chote Miyan","genre":"Action Comedy","lead_actor":"Akshay Kumar","director":"Ali Abbas Zafar","imdb_rating":3.6,"verdict":"Flop","release_year":2024},
    {"movie_name":"Welcome","genre":"Comedy Action","lead_actor":"Akshay Kumar","director":"Anees Bazmee","imdb_rating":7.4,"verdict":"Blockbuster","release_year":2007},
    {"movie_name":"Raid","genre":"Thriller Drama","lead_actor":"Ajay Devgn","director":"Raj Kumar Gupta","imdb_rating":7.6,"verdict":"Hit","release_year":2018},
    {"movie_name":"Maidaan","genre":"Drama Sports","lead_actor":"Ajay Devgn","director":"Amit Ravindernath Sharma","imdb_rating":8.3,"verdict":"Average","release_year":2024},
    {"movie_name":"Shaitaan","genre":"Horror Thriller","lead_actor":"Ajay Devgn","director":"Vikas Bahl","imdb_rating":7.0,"verdict":"Hit","release_year":2024},
    {"movie_name":"Do Aur Do Pyaar","genre":"Romance Drama","lead_actor":"Vidya Balan","director":"Shirsha Guha Thakurta","imdb_rating":7.2,"verdict":"Average","release_year":2024},
    {"movie_name":"Crew","genre":"Comedy Thriller","lead_actor":"Kareena Kapoor","director":"Rajesh A Krishnan","imdb_rating":6.5,"verdict":"Hit","release_year":2024},
    {"movie_name":"Merry Christmas","genre":"Thriller Romance","lead_actor":"Vijay Sethupathi","director":"Sriram Raghavan","imdb_rating":7.6,"verdict":"Average","release_year":2024},
    {"movie_name":"Guntur Kaaram","genre":"Drama Family","lead_actor":"Mahesh Babu","director":"Trivikram Srinivas","imdb_rating":6.2,"verdict":"Average","release_year":2024},
    {"movie_name":"HanuMan","genre":"Action Fantasy","lead_actor":"Teja Sajja","director":"Prasanth Varma","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Premalu","genre":"Romance Comedy","lead_actor":"Naslen","director":"Girish AD","imdb_rating":8.4,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Manjummel Boys","genre":"Adventure Drama","lead_actor":"Soubin Shahir","director":"Chidambaram","imdb_rating":8.5,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Aavesham","genre":"Action Comedy","lead_actor":"Fahadh Faasil","director":"Jithu Madhavan","imdb_rating":8.3,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Maharaja","genre":"Action Thriller","lead_actor":"Vijay Sethupathi","director":"Nithilan Swaminathan","imdb_rating":8.5,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Lucky Baskhar","genre":"Drama Thriller","lead_actor":"Dulquer Salmaan","director":"Venky Atluri","imdb_rating":8.3,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Singham Returns","genre":"Action Drama","lead_actor":"Ajay Devgn","director":"Rohit Shetty","imdb_rating":5.0,"verdict":"Average","release_year":2024},
    {"movie_name":"Bhool Bhulaiyaa 3","genre":"Horror Comedy","lead_actor":"Kartik Aaryan","director":"Anees Bazmee","imdb_rating":6.5,"verdict":"Blockbuster","release_year":2024},
    {"movie_name":"Bhool Bhulaiyaa 2","genre":"Horror Comedy","lead_actor":"Kartik Aaryan","director":"Anees Bazmee","imdb_rating":6.8,"verdict":"Blockbuster","release_year":2022},
    {"movie_name":"Shehzada","genre":"Action Drama","lead_actor":"Kartik Aaryan","director":"Rohit Dhawan","imdb_rating":5.5,"verdict":"Flop","release_year":2023},
    {"movie_name":"Chandu Champion","genre":"Biography Sports","lead_actor":"Kartik Aaryan","director":"Kabir Khan","imdb_rating":8.0,"verdict":"Average","release_year":2024},
    {"movie_name":"Sonu Ke Titu Ki Sweety","genre":"Romance Comedy","lead_actor":"Kartik Aaryan","director":"Luv Ranjan","imdb_rating":7.1,"verdict":"Blockbuster","release_year":2018},
    {"movie_name":"Kho Gaye Hum Kahan","genre":"Drama","lead_actor":"Siddhant Chaturvedi","director":"Arjun Varain Singh","imdb_rating":7.4,"verdict":"Hit","release_year":2023},
    {"movie_name":"Dil Chahta Hai","genre":"Drama Comedy","lead_actor":"Aamir Khan","director":"Farhan Akhtar","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2001},
    {"movie_name":"Rang De Basanti","genre":"Drama Action","lead_actor":"Aamir Khan","director":"Rakeysh Omprakash Mehra","imdb_rating":8.1,"verdict":"Blockbuster","release_year":2006},
    {"movie_name":"Swades","genre":"Drama","lead_actor":"Shah Rukh Khan","director":"Ashutosh Gowariker","imdb_rating":8.2,"verdict":"Average","release_year":2004},
    {"movie_name":"Kal Ho Naa Ho","genre":"Romance Drama","lead_actor":"Shah Rukh Khan","director":"Nikhil Advani","imdb_rating":7.9,"verdict":"Blockbuster","release_year":2003},
    {"movie_name":"Mughal-E-Azam","genre":"Drama Romance","lead_actor":"Dilip Kumar","director":"K Asif","imdb_rating":8.2,"verdict":"Blockbuster","release_year":1960},
    {"movie_name":"Mother India","genre":"Drama","lead_actor":"Nargis","director":"Mehboob Khan","imdb_rating":8.0,"verdict":"Blockbuster","release_year":1957},
    {"movie_name":"Guide","genre":"Drama Romance","lead_actor":"Dev Anand","director":"Vijay Anand","imdb_rating":8.1,"verdict":"Blockbuster","release_year":1965},
    {"movie_name":"Anand","genre":"Drama","lead_actor":"Rajesh Khanna","director":"Hrishikesh Mukherjee","imdb_rating":8.1,"verdict":"Blockbuster","release_year":1971},
    {"movie_name":"Mughal E Azam","genre":"Drama Romance","lead_actor":"Dilip Kumar","director":"K Asif","imdb_rating":8.2,"verdict":"Blockbuster","release_year":1960},
]

df = pd.DataFrame(bollywood_data)
df['genre'] = df['genre'].fillna('')
df['lead_actor'] = df['lead_actor'].fillna('')
df['director'] = df['director'].fillna('')
df['combined'] = df['genre'] + ' ' + df['lead_actor'] + ' ' + df['director']

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined'])
similarity = cosine_similarity(tfidf_matrix)

sim_df = pd.DataFrame(
    similarity,
    index=df['movie_name'].values,
    columns=df['movie_name'].values
)

sim_df.to_pickle('bollywood_similarity.pkl')
df.to_pickle('bollywood_df.pkl')

print(f"Total Bollywood movies: {len(df)}")
print("Saved! bollywood_similarity.pkl created.")